# Generated by Django 4.2.1 on 2023-05-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_likes_delete_cafe_delete_convenience_delete_gym_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='name',
        ),
        migrations.AddField(
            model_name='likes',
            name='like',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
