# Generated by Django 4.2.1 on 2023-05-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_likesresult_alter_likes_liked_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likes',
        ),
    ]
