# Generated by Django 4.2.1 on 2023-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_remove_likesresult_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesresult',
            name='like_state',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
