# Generated by Django 4.2.1 on 2023-05-29 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addr_code', models.CharField(max_length=21)),
                ('province_name', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
                ('dong', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username_comment', models.CharField(max_length=10, null=True)),
                ('addr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.addressresult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
