# Generated by Django 4.2.1 on 2023-05-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_addressresult_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=21, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, db_column='City', max_length=10, null=True)),
                ('district', models.CharField(blank=True, db_column='District', max_length=10, null=True)),
                ('dong', models.CharField(blank=True, db_column='Dong', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Address',
                'managed': True,
            },
        ),
    ]
