# Generated by Django 4.2.1 on 2023-05-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_comment_username_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='code_comment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='input_addr',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
