# Generated by Django 4.2.1 on 2023-05-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_comment_code_comment_comment_input_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
